version: 2.1
jobs:
  build:
    docker:
      - image: "buildpack-deps:bionic"
    steps:
      - checkout
  request-testing:
    docker:
      - image: "buildpack-deps:bionic"
      - run:
          name: PrintEnv
          command: printenv

    steps:
      - run:
          name: Do nothing really
          command: printenv

workflows:
  build_and_test:
    jobs:
      - build
      - request-testing:
          type: approval
          requires:
            - build